name: vcl
# author: Aliaksei Liulis <lai@tut.by>
description: Dart implementation of vcl interface C++Builder, Delphi.
version: 1.0.2
homepage: https://github.com/ds-42/dart-vcl

environment:
  sdk: '>=2.13.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0

dependencies:
  sprintf: ^6.0.0